swagger:
  version: '1.5.0'
  schemes: 'http,https'
server:
  port: 8004
  servlet:
    path: '/documentManagement/v1'
management:
  defaults:
    enabled: false
  endpoints:
    enabled-by-default: false
spring:
  profiles:
    active: log-debug,common
  jackson:
    time-zone: Europe/Zagreb
  output:
    ansi:
      enabled: always
  liquibase:
    enabled: false
